### ISSUE TITLE
Codestyle in `buildinfo` and `repro`

### ISSUE THREAD

**Issue by Foxboron** [archlinux/archlinux-repro#52]
The codestyles differ a bit so we should try stick to one style. I think `buildinfo` is a good starting ground as most of it is commented and stuff.

@coderobe could probably layout some basics.

**Comment by jelly** [comment]
Is there a sane linter for bash code style?

**Comment by coderobe** [comment]
shellcheck is more of a semantic linter rather than a style linter.

buildinfo passes shellcheck, and if the other files don't that should probably be fixed.

i'm not sure whether there is any formalized code style that could even be linted properly - though sticking to the way buildinfo is currently written would be a good idea, i think it's pretty clear and well commented
